[tool.poetry]
name = "myskoda"
version = "0.3.0"
description = "Library for interaction with the MySkoda APIs."
authors = ["Frederick Gnodtke <frederick@gnodtke.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12.0"
beautifulsoup4 = "^4"
aiohttp = "^3"
pyjwt = "^2"
pyyaml = "^6"
pydantic = "^1"
asyncio = "^3"
asyncclick = { version = "^8.1.7.2", optional = true }
termcolor = { version = "^2.4.0", optional = true }
paho-mqtt = "^1"
coloredlogs = {version = "^15.0.1", optional = true}
asyncio-paho = "^0.6.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"
pyright = "^1.1.379"

[tool.poetry.scripts]
myskoda = "myskoda.cli:cli"

[tool.poetry.extras]
cli = ["asyncclick", "coloredlogs", "termcolor"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # missing-trailing-comma
    "D101",   # undocumented-public-class
    "D103",   # undocumented-public-function
    "D203",   # one-blank-line-before-class
    "D211",   # blank-line-before-class
    "D213",   # multi-line-summary-second-line
    "FIX002", # line-contains-todo
    "G004",   # logging-f-string
    "ISC001", # single-line-implicit-string-concatenation
    "T201",   # print
    "TD003",  # missing-todo-link
]
