[tool.poetry]
name = "myskoda"
version = "0.1.0"
description = "Library for interaction with the MySkoda APIs."
authors = ["Frederick Gnodtke <frederick@gnodtke.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
beautifulsoup4 = "^4.12.3"
aiohttp = "^3.10.5"
pyjwt = "^2.9.0"
pyyaml = "^6.0.2"
asyncio = "^3.4.3"


[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"
pyright = "^1.1.379"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportIncompatibleVariableOverride = "none"