[tool.poetry]
name = "myskoda"
version = "0.5.1"
description = "Library for interaction with the MySkoda APIs."
authors = ["Frederick Gnodtke <frederick@gnodtke.net>"]
readme = "README.md"

[tool.poetry.dependencies]
aiohttp = "^3"
asyncclick = { version = "^8.1.7.2", optional = true }
asyncio = "^3"
asyncio-paho = "^0.6.0"
beautifulsoup4 = "^4"
coloredlogs = { version = "^15.0.1", optional = true }
paho-mqtt = "^1"
pydantic = "^1"
pyjwt = "^2"
python = ">=3.12.0"
pyyaml = "^6"
termcolor = { version = "^2.4.0", optional = true }

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.379"
pytest = "^8"
pytest-asyncio = "^0"
ruff = "^0.6.4"

[tool.poetry.scripts]
myskoda = "myskoda.cli:cli"

[tool.poetry.extras]
cli = ["asyncclick", "coloredlogs", "termcolor"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "COM812", # missing-trailing-comma
    "D101",   # undocumented-public-class
    "D103",   # undocumented-public-function
    "D203",   # one-blank-line-before-class
    "D211",   # blank-line-before-class
    "D213",   # multi-line-summary-second-line
    "FBT001", # boolean-type-hint-positional-argument
    "FIX002", # line-contains-todo
    "G004",   # logging-f-string
    "ISC001", # single-line-implicit-string-concatenation
    "S101",   # assert (used in tests)
    "T201",   # print
    "TD003",  # missing-todo-link
]
select = ["ALL"]
